AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance, an S3 bucket, and an EMR Cluster

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9  # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
      Tags:
        - Key: Name
          Value: Vita
  
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vita1234-unique  # Ensure this bucket name is globally unique

  # Example of adding an EMR Cluster
  MyEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: MyCluster
      ReleaseLabel: emr-6.4.0
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m5.xlarge
        TerminationProtected: false
      Applications:
        - Name: Hadoop
        - Name: Spark
      VisibleToAllUsers: true
      LogUri: !Sub 's3://${WebAppBucket}/logs/'
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
