AWSTemplateFormatVersion: 2010-09-09
Description: Create an EMR Cluster and download data from Kaggle

Resources:
  MyEMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: MyEMRCluster
      ReleaseLabel: emr-6.4.0  # Use the appropriate EMR release version
      Instances:
        MasterInstanceGroup:
          InstanceCount: 1
          InstanceType: m5.xlarge
        CoreInstanceGroup:
          InstanceCount: 2
          InstanceType: m5.xlarge
        TerminationProtected: false
      Applications:
        - Name: Hadoop
        - Name: Spark
      LogUri: !Sub 's3://${LogBucket}/logs/'
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      BootstrapActions:
        - Name: Install Kaggle CLI
          ScriptBootstrapAction:
            Path: !Sub 'https://raw.githubusercontent.com/snehal014/project88/main/.github/workflows/kaggle_cli.sh'
            Args: []
      Steps:
        - Name: Download Kaggle Data
          ActionOnFailure: TERMINATE_CLUSTER
          HadoopJarStep:
            Jar: command-runner.jar
            Args:
              - hive-script
              - !Sub |
                kaggle datasets download -d mrisdal/exploring-survival-on-the-titanic -p /home/hadoop/
                unzip /home/hadoop/dataset.zip -d /home/hadoop/
            
  LogBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-emr-logs-bucket-unique  # Ensure this bucket name is unique

  ScriptBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-emr-scripts-bucket-unique  # Ensure this bucket name is unique
