---
AWSTemplateFormatVersion: 2010-09-09
Description: create ec2 instance and s3 bucket

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9 # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
  MyS3Bucket:
    Type: AWS::S3::Bucket
      BucketName: group6august24
Outputs:
    BucketName:
      Description: group6august24
      Value: !Ref MyS3Bucket
