AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance and an S3 bucket and an EMR Cluster

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0d5eff06f840b45e9  # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
  
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vita12345

  EMRCluster:
    Type: AWS::EMR::Cluster
    Properties:
      Name: "MyEMRCluster"
      ReleaseLabel: emr-6.10.0    
      Applications:
        -Name: Hadoop
        -Name: Spark
      Instances:
        MasterInstanceType: m5.xlarge
        SlaveInstanceType: m5.xlarge
        Instancecount: 2
        EC2SubnetId: subnet-0867486a2c91c88c8
        KeepJobFlowAliveWhenNoSeps: true
      JobFlowRole: EMR_EC2_DefaultRole
      ServiceRole: EMR_DefaultRole
      LogUri: !Sub "s3://${WebAppBucket}/logs/"
