AWSTemplateFormatVersion: 2010-09-09
Description: Create an EC2 instance and an S3 bucket and an EMR Cluster

Resources:
  WebAppInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceName: Snehal
      ImageId: ami-0d5eff06f840b45e9  # ImageID valid only in us-east-1 region
      InstanceType: t2.micro
  
  WebAppBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: vita12345

